### ISSUE TITLE
can't create an issue in application

### ISSUE THREAD

**Issue by mckilleron** [renatomarinho/laravel-gitscrum#61]
I can't create an issue, i've got this result :

![issue](https://cloud.githubusercontent.com/assets/23717316/21175957/11cc263a-c1e5-11e6-89c6-766e36875b5f.png)

**Comment by yinx** [comment]
@mckilleron I can't seem to recreate this error.
Can you try to recreate it and let me know which steps you took to make this error happen?

**Comment by mckilleron** [comment]
Same when i try to create a new product backlog

![error2](https://cloud.githubusercontent.com/assets/23717316/21177918/760caeb4-c1ed-11e6-84c7-ee99507b9918.png)

**Comment by yinx** [comment]
@mckilleron Thanks.
I have pinpointed the issue and I'll see if i can get it resolved.

**Comment by mckilleron** [comment]
You have reproduce ?

**Comment by yinx** [comment]
@mckilleron Yes thank you I'm looking into resolving it.

**Comment by yinx** [comment]
@renatomarinho This error happens because of the hidden is_api field. I currently have no time to look into this to check what it is used for but removing that hidden field fixes this issue.
I'll check in on this again tonight

**Comment by renatomarinho** [comment]
@mckilleron  @yinx Do a pulll and try again and check if bug is fixed.

The GitHub API v3 don't allow create a new repository for user authenticated. https://developer.github.com/v3/repos/#create - this logic still is not implemented in GitScrum, I am working.

In the GitScrum each Product Backlog is a Repository to GitHub.

**Comment by mckilleron** [comment]
Fixed now !

**Comment by yinx** [comment]
I am still seeing this issue when trying to add a new product backlog.
Removing the hidden is_api field does solve it but I currently don't know what that field affects.

**Comment by mckilleron** [comment]
Fixed for me for issue part, but same for add new product backlog
